name: Image Conversion

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Allows the action to commit to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install webp and imagemagick
        run: |
          sudo apt-get update
          sudo apt-get install -y webp imagemagick

      - name: Convert images to WebP
        run: |
          # Find all png files in the current directory
          for file in sticker*.png; do
            # Check if the webp version already exists
            if [ ! -f "${file%.png}.webp" ]; then
              echo "Converting $file to webp"
              # Convert the image to webp and resize it to a max width of 1000px
              convert "$file" -resize "1000>" "${file%.png}.webp"
            fi
          done

      - name: Commit files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Add converted webp images"
            git push
          else
            echo "No changes to commit"
          fi
