name: Convert PNG to WebP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'png/**.png'

jobs:
  convert:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Debug and Install webp
      run: |
        set -x # Enable shell debugging
        brew update # Update Homebrew first
        brew install webp
        if ! command -v cwebp &> /dev/null; then
            echo "cwebp not found after installation!"
            exit 1
        fi

    - name: Convert PNG to WebP and resize
      run: |
        set -x # Enable shell debugging
        ulimit -n 4096 # Increase open file limit
        mkdir -p webp
        for file in png/*.png; do
          filename=$(basename "$file" .png)
          cwebp "$file" -o "webp/$filename.webp" -resize 1000 0
        done

    - name: Commit WebP files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs(webp): Automate PNG to WebP conversion"
        file_pattern: webp/*.webp
        token: ${{ secrets.PERSONAL_TOKEN }}
