name: Convert PNG to WebP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'png/**.png'

jobs:
  convert:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install webp
      run: brew install webp

    - name: Convert PNG to WebP and resize
      run: |
        mkdir -p webp
        for file in png/*.png; do
          filename=$(basename "$file" .png)
          cwebp "$file" -o "webp/$filename.webp" -resize 1000 0
        done

    - name: Commit WebP files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "docs(webp): Automate PNG to WebP conversion"
        file_pattern: webp/*.webp
